version: "3.7"

services:
  my-backedn:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
      - ./swagger/starbucks-swagger.js:/myfolder/swagger/starbucks-swagger.js
      - ./swagger/token-swagger.js:/myfolder/swagger/token-swagger.js
      - ./swagger/user-swagger.js:/myfolder/swagger/user-swagger.js
    ports:
      - 3000:3000


  my-database:
    image: mongo:5
    ports:
      - 27017:27017
